/// AI feature module — provides all Riverpod providers related to
/// Google Gemini AI integration for document summarization, data
/// extraction, and intelligent content analysis.
///
/// The module exposes the Gemini service, AI repository for persisting
/// AI-generated results, and use cases for summarization and extraction.
library;

import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../domain/repositories/ai_repository.dart';
import '../../domain/usecases/ai/summarize_document_usecase.dart';
import '../../domain/usecases/ai/extract_data_usecase.dart';
import '../../domain/usecases/ai/classify_document_usecase.dart';
import '../../data/datasources/ai_local_data_source.dart';
import '../../data/repositories/ai_repository_impl.dart';
import '../injection.dart';

// ---------------------------------------------------------------------------
// Data Sources
// ---------------------------------------------------------------------------

/// Local data source that caches AI-generated summaries, extracted data,
/// and document classifications in Hive for offline access.
final aiLocalDataSourceProvider = Provider<AILocalDataSource>((ref) {
  final box = ref.watch(hiveBoxProvider);
  return AILocalDataSource(box: box);
});

// ---------------------------------------------------------------------------
// Services
// ---------------------------------------------------------------------------

/// Gemini AI service wrapping the Google Generative AI SDK.
///
/// Supports multimodal input (text + images) for document analysis.
/// Requires a valid API key configured in the app's secure storage.
final geminiServiceProvider = Provider<GeminiService>((ref) {
  final isOnline = ref.watch(isOnlineProvider);
  return GeminiService(isOnline: isOnline);
});

// ---------------------------------------------------------------------------
// Repository
// ---------------------------------------------------------------------------

/// Primary [AIRepository] implementation backed by the Gemini service
/// and local Hive cache.
final aiRepositoryProvider = Provider<AIRepository>((ref) {
  final localDataSource = ref.watch(aiLocalDataSourceProvider);
  final geminiService = ref.watch(geminiServiceProvider);
  return AIRepositoryImpl(
    localDataSource: localDataSource,
    geminiService: geminiService,
  );
});

// ---------------------------------------------------------------------------
// Use Cases
// ---------------------------------------------------------------------------

/// Generates a concise summary of the document at [documentId] using
/// Gemini. Returns a [DocumentSummary] with key points and a one-line
/// TL;DR.
final summarizeDocumentUseCaseProvider =
    Provider<SummarizeDocumentUseCase>((ref) {
  final repository = ref.watch(aiRepositoryProvider);
  return SummarizeDocumentUseCase(repository: repository);
});

/// Extracts structured data (tables, key-value pairs, dates, amounts)
/// from a document using Gemini's multimodal capabilities.
final extractDataUseCaseProvider = Provider<ExtractDataUseCase>((ref) {
  final repository = ref.watch(aiRepositoryProvider);
  return ExtractDataUseCase(repository: repository);
});

/// Classifies a document into a category (invoice, receipt, contract,
/// ID, notes, etc.) using Gemini for intelligent folder suggestions.
final classifyDocumentUseCaseProvider =
    Provider<ClassifyDocumentUseCase>((ref) {
  final repository = ref.watch(aiRepositoryProvider);
  return ClassifyDocumentUseCase(repository: repository);
});

// ---------------------------------------------------------------------------
// Service Class & Models (inline for DI wiring)
// ---------------------------------------------------------------------------

/// Wraps the Google Generative AI (Gemini) SDK for document analysis.
class GeminiService {
  GeminiService({this.isOnline = false});

  /// Whether the device has network connectivity for cloud-based AI.
  final bool isOnline;

  /// Generates a summary of the document text at [content].
  /// When [imagePaths] are provided, uses multimodal input.
  Future<DocumentSummary> summarize(
    String content, {
    List<String>? imagePaths,
  }) async {
    throw UnimplementedError('GeminiService.summarize must be implemented');
  }

  /// Extracts structured data from the document content.
  /// Returns a map of field names to extracted values.
  Future<ExtractedData> extractData(
    String content, {
    List<String>? imagePaths,
    List<String>? fields,
  }) async {
    throw UnimplementedError('GeminiService.extractData must be implemented');
  }

  /// Classifies the document into a semantic category.
  Future<DocumentClassification> classify(
    String content, {
    List<String>? imagePaths,
  }) async {
    throw UnimplementedError('GeminiService.classify must be implemented');
  }
}

/// Structured summary of a document generated by Gemini.
class DocumentSummary {
  const DocumentSummary({
    required this.id,
    required this.documentId,
    required this.summary,
    required this.keyPoints,
    required this.tldr,
    required this.generatedAt,
  });

  /// Unique identifier for this summary.
  final String id;

  /// ID of the source document.
  final String documentId;

  /// Multi-paragraph summary of the document content.
  final String summary;

  /// Bullet-point list of key takeaways.
  final List<String> keyPoints;

  /// One-line "too long; didn't read" summary.
  final String tldr;

  /// Timestamp when the summary was generated.
  final DateTime generatedAt;
}

/// Structured data extracted from a document by Gemini.
class ExtractedData {
  const ExtractedData({
    required this.id,
    required this.documentId,
    required this.fields,
    required this.tables,
    required this.extractedAt,
  });

  /// Unique identifier for this extraction.
  final String id;

  /// ID of the source document.
  final String documentId;

  /// Key-value pairs of extracted fields (e.g., 'total': '\$42.50').
  final Map<String, String> fields;

  /// Extracted table data as rows of string maps.
  final List<Map<String, String>> tables;

  /// Timestamp when the extraction was performed.
  final DateTime extractedAt;
}

/// Classification result for a document.
class DocumentClassification {
  const DocumentClassification({
    required this.category,
    required this.confidence,
    required this.suggestedFolder,
    required this.tags,
  });

  /// Primary document category (e.g., 'invoice', 'receipt', 'contract').
  final String category;

  /// Confidence score for the classification (0.0–1.0).
  final double confidence;

  /// Suggested folder name based on the classification.
  final String suggestedFolder;

  /// Additional tags for fine-grained categorization.
  final List<String> tags;
}
